(function () {
  const root=(window.TL&&window.TL.$?window.TL.$('#proyectos'):document.querySelector('#proyectos')); if(!root)return;
  const data={
    koben:{name:'KÓOBEN',badge:'Beta',badgeClass:'badge--beta',type:'ecosistema digital',image:'./frontend/src/assets/cases/koben-hero.jpg',alt:'Vista de Kóoben',summary:'Una experiencia beta para explorar una relación digital con clientes y negocios.',problem:'Kóoben explora cómo una experiencia digital puede acercar a un negocio y a sus clientes.',url:'https://fershopool.github.io/koooben-beta/#inicio',functions:[['Login','prototipo'],['Código QR','prototipo'],['Wallet','sin configurar'],['Panel','datos de ejemplo']]},
    clinica:{name:'CLÍNICA SAN PEDRO',badge:'Publicado',badgeClass:'badge--disponible',type:'sitio institucional',image:'./frontend/src/assets/cases/clinica-hero.jpg',alt:'Vista de Clínica San Pedro',summary:'Un sitio institucional publicado para presentar la clínica y orientar a sus visitantes.',problem:'La información de una clínica necesita un lugar claro, confiable y fácil de recorrer.',url:'https://fershopool.github.io/clinica-san-pedro-de-los-pinos/',functions:[['Sitio institucional','disponible'],['Información de la clínica','disponible'],['Navegación web','disponible']]},
    ollin:{name:'OLLIN',badge:'En desarrollo',badgeClass:'badge--capacidad',type:'ecosistema conceptual',image:'./frontend/src/assets/cases/ollin-hero.jpg',alt:'Vista de Ollin',summary:'Un ecosistema conceptual en desarrollo para ordenar una experiencia digital propia.',problem:'OLLIN está tomando forma: el reto es convertir una idea amplia en una experiencia que pueda crecer.',url:'https://fershopool.github.io/ollin-site/',functions:[['Experiencia web','en desarrollo'],['Ecosistema digital','capacidad'],['Módulos futuros','próximamente']]},
    calpulli:{name:'UPIICSA CALPULLI',badge:'En desarrollo',badgeClass:'badge--capacidad',type:'ecosistema académico',image:'./frontend/src/assets/cases/calpulli-hero.jpg',alt:'Vista de UPIICSA Calpulli',summary:'Una propuesta en desarrollo para reunir funciones y mapa dentro de una experiencia académica.',problem:'Calpulli necesita que sus funciones y su territorio puedan leerse como una sola experiencia.',url:'https://fershopool.github.io/upiicsa-calpulli-site/',functions:[['Funciones','en desarrollo'],['Mapa','próximamente'],['Experiencia académica','capacidad']]},
    cuicoyan:{name:'CUICOYAN',badge:'Publicado',badgeClass:'badge--disponible',type:'plataforma cultural',image:'./frontend/src/assets/cases/cuicoyan-hero.jpg',alt:'Vista de Cuicoyan',summary:'Una plataforma publicada para descubrir eventos, artistas, foros y experiencias culturales en CDMX.',problem:'La oferta cultural de una ciudad está dispersa; Cuicoyan la reúne para que cada persona encuentre su próximo plan.',url:'https://fershopool.github.io/cuicoyan-site/',functions:[['Eventos, artistas y foros','disponible'],['Búsqueda de planes','disponible'],['Mapa y exploración','disponible'],['Navegación móvil','disponible']]}
  };
  const items=[...root.querySelectorAll('[data-project]')], feature=root.querySelector('[data-project-feature]'), badge=root.querySelector('[data-project-badge]'), count=root.querySelector('[data-project-count]'), image=root.querySelector('[data-project-image]'), type=root.querySelector('[data-project-type]'), title=root.querySelector('[data-project-title]'), summary=root.querySelector('[data-project-summary]'), dialog=root.querySelector('[data-project-dialog]'), dialogTitle=root.querySelector('[data-dialog-title]'), dialogState=root.querySelector('[data-dialog-state]'), dialogProblem=root.querySelector('[data-dialog-problem]'), dialogFunctions=root.querySelector('[data-dialog-functions]'), external=root.querySelector('[data-dialog-external]'), liveButton=root.querySelector('[data-dialog-live]'), live=root.querySelector('[data-live-frame]'); let active='koben', lastTrigger;
  const paint=(key)=>{const item=data[key];if(!item)return;active=key;items.forEach((button,index)=>{const on=button.dataset.project===key;button.classList.toggle('is-active',on);button.setAttribute('aria-pressed',String(on));if(on)count.textContent=`${String(index+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}`;});badge.className=`badge ${item.badgeClass}`;badge.textContent=item.badge;image.src=item.image;image.alt=item.alt;type.textContent=item.type;title.textContent=item.name;summary.textContent=item.summary;root.style.setProperty('--project-accent',key==='clinica'?'#8EAC69':key==='ollin'?'#D9A64C':key==='calpulli'?'#E2A263':key==='cuicoyan'?'#FF5CA8':'#D9A64C');};
  const showDetails=(trigger)=>{const item=data[active];lastTrigger=trigger;dialogTitle.textContent=item.name;dialogState.textContent=item.badge;dialogProblem.textContent=item.problem;external.href=item.url;dialogFunctions.replaceChildren(...item.functions.map(([label,state])=>{const li=document.createElement('li');li.textContent=label;const small=document.createElement('small');small.textContent=state;li.append(small);return li;}));live.replaceChildren();if(dialog.showModal)dialog.showModal();else{dialog.setAttribute('open','');dialog.classList.add('is-open');}root.querySelector('[data-dialog-close]')?.focus();};
  const hideDetails=()=>{if(dialog.open&&dialog.close)dialog.close();else{dialog.removeAttribute('open');dialog.classList.remove('is-open');}lastTrigger?.focus();};
  items.forEach((button)=>button.addEventListener('click',()=>paint(button.dataset.project)));root.querySelector('[data-project-details]')?.addEventListener('click',(event)=>showDetails(event.currentTarget));root.querySelector('[data-dialog-close]')?.addEventListener('click',hideDetails);dialog?.addEventListener('click',(event)=>{if(event.target===dialog)hideDetails();});dialog?.addEventListener('cancel',(event)=>{event.preventDefault();hideDetails();});
  liveButton?.addEventListener('click',()=>{const item=data[active];live.replaceChildren();const phone=document.createElement('div');phone.className='s-proyectos__phone';const frame=document.createElement('iframe');frame.src=item.url;frame.title=`Vista en vivo de ${item.name}`;frame.loading='lazy';frame.referrerPolicy='no-referrer-when-downgrade';frame.sandbox='allow-scripts allow-forms allow-same-origin allow-popups';phone.append(frame);live.append(phone);liveButton.disabled=true;liveButton.setAttribute('aria-label',`Vista en vivo cargada de ${item.name}`);});
  paint(active);
}());
